### ISSUE TITLE
Use .gitignore to remove logs from the repo

### ISSUE THREAD

**Issue by tgglv** [KokkieH/Custom-Woo-Project#1]
Hey @KokkieH!

I noticed the following change in your last commit https://github.com/KokkieH/Custom-Woo-Project/commit/f73ea37adca325d25cf50570e1c7e1ca1f41a0cc:
![image](https://user-images.githubusercontent.com/15897544/145422744-1997243a-f11c-415d-99e1-f8e34be4313c.png)

Logs look more related to operating the application rather than the part of its developments. Because of that they should be removed from the repo and ignored.

To achieve this, please become familiar with [.gitignore](https://git-scm.com/docs/gitignore) (for sure if you don't know about it yet) and ignore all files for both `php` and `nginx` folders.

As a result, your repo shouldn't contain logs anymore but the new file .gitignore should be added in `./logs` folder. It might contain the following:
```
php
nginx
```

**Comment by KokkieH** [comment]
I ended up coming at this from a different direction - I realised for the purposes of this project it's not really necessary to sync the entire project folder that Local created, so I changed the parent folder for the repository to the `public` folder that contains the actual WordPress files.

But I have added a `.gitignore` file, using the [template for WordPress found here](https://github.com/github/gitignore/blob/main/WordPress.gitignore).

**Comment by tgglv** [comment]
Brilliant! That's much better!
