### ISSUE TITLE
Create REST API endpoint for fetching commits

### ISSUE THREAD

**Issue by tgglv** [KokkieH/Custom-Woo-Project#5]
## Preface

Currently, we fetch external data (commit metadata) with the use of `wp_remote_get` and `wp_remote_retrieve_body`. In the future we want our Gutenberg Block to fetch that data for us. But GB block shouldn't know much about the Github repository URL (assume it's sensitive data since external resources might be accessible with additional authentication). Instead, we want to access data with the use of the commit's hash.

To reach our goal we'll create a REST API endpoint that will provide this data for us by a commit's name.

The general data about custom REST API endpoints in WP: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

#### New REST API Controller
1. Create a directory `include` in the `gh-commit-widget` plugin directory.

2. Create a new class there with the name `class-rest-api.php` with the following content:
```php
<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class KokkieH_REST_API {
}
```

3. Register a new endpoint by adding the following in the new class
```php

    public function __construct() {
        add_action( 'rest_api_init', array( $this, 'register_endpoints' ) );
    }

    public function register_endpoints() {
        register_rest_route(
            'kokkieh', 
            '/commit/(?P<id>\w{40})', 
            array(
                'methods' => 'GET',
                'callback' => array( $this, 'get_commit' ),
            )
        );
    }
```

4. Add `get_commit` handler 
```php
    public function get_commit( $data ) {
        $commit_url = $this->get_url( $data['id'] );
        $commit_request = wp_remote_get( $commit_url );
        if ( is_wp_error( $commit_request ) ) {
            return false;
        }

        $commit_body = wp_remote_retrieve_body( $commit_request );
        return json_decode( $commit_body, true );
    }

    private function get_url( $commit_hash ) {
        return "https://api.github.com/repos/KokkieH/Advent-of-Code-2021/commits/{$commit_hash}";
    }
```

5. Start using new REST API controller in our main plugin file:
```php
require_once __DIR__ . '/include/class-rest-api.php';
new KokkieH_REST_API();
```

6. Modify getting a value for `$commit_url`:
```php
$commit_hash = 'eb1d6e113014a1c6fbfc0c4b8e7420b29d98d131';
$commit_url = site_url( '/wp-json/kokkieh/commit/' . $commit_hash );
```

**Comment by KokkieH** [comment]
Completed
